var price = 100;
console.log(typeof price);
var price = '100';
console.log(typeof price);
var isHappy = true;
console.log(typeof isHappy);
var romantic;
console.log(typeof romantic);
var sum1 = 0.1;
var sum2 = 0.2;
var sum = sum1 + sum2;
sum = sum.toFixed(2);
sum = parseFloat(sum);
console.log(sum);